/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.4.0
 */

export type CampaignCreationV2Sensitivity =
  (typeof CampaignCreationV2Sensitivity)[keyof typeof CampaignCreationV2Sensitivity]

export const CampaignCreationV2Sensitivity = {
  NORMAL: 'NORMAL',
  SENSITIVE: 'SENSITIVE',
} as const
