/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.4.0
 */
import type { CampaignCreationSensitivity } from './campaignCreationSensitivity'
import type { MetadataCreation } from './metadataCreation'

export interface CampaignCreation {
  id?: string
  /** @minLength 1 */
  label: string
  sensitivity?: CampaignCreationSensitivity
  /** @minItems 1 */
  questionnaireIds: string[]
  metadata?: MetadataCreation
}
