/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.4.0
 */
import type { CampaignSummarySensitivity } from './campaignSummarySensitivity'

export interface CampaignSummary {
  id?: string
  sensitivity?: CampaignSummarySensitivity
  questionnaireIds?: string[]
}
