/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.4.0
 */

export type CampaignSensitivity =
  (typeof CampaignSensitivity)[keyof typeof CampaignSensitivity]

export const CampaignSensitivity = {
  NORMAL: 'NORMAL',
  SENSITIVE: 'SENSITIVE',
} as const
