/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.4.0
 */

export type CampaignSummarySensitivity =
  (typeof CampaignSummarySensitivity)[keyof typeof CampaignSummarySensitivity]

export const CampaignSummarySensitivity = {
  NORMAL: 'NORMAL',
  SENSITIVE: 'SENSITIVE',
} as const
