/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.4.0
 */
import type { StateData } from './stateData'

export interface InterrogationStateDto {
  id?: string
  surveyUnitId?: string
  questionnaireId?: string
  campaignId?: string
  stateData?: StateData
}
