/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.4.0
 */
import type { CollectedData } from './collectedData'
import type { StateDataUpdate } from './stateDataUpdate'

export interface InterrogationDataStateDataUpdate {
  data?: CollectedData
  stateData: StateDataUpdate
}
