/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.4.0
 */
import type { InterrogationMetadataContext } from './interrogationMetadataContext'
import type { Logos } from './logos'
import type { MetadataVariable } from './metadataVariable'
import type { Personalization } from './personalization'

export interface InterrogationMetadata {
  context: InterrogationMetadataContext
  personalization?: Personalization
  label: string
  objectives: string
  variables?: MetadataVariable[]
  logos?: Logos
}
