/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.4.0
 */

export type IntegrationResultUnitStatus =
  (typeof IntegrationResultUnitStatus)[keyof typeof IntegrationResultUnitStatus]

export const IntegrationResultUnitStatus = {
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  ERROR: 'ERROR',
} as const
