/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.4.0
 */
import type { InterrogationTempZoneInput } from './interrogationTempZoneInput'

export interface InterrogationTempZone {
  id?: string
  interrogationId?: string
  userId?: string
  date?: number
  interrogation?: InterrogationTempZoneInput
}
