/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.4.0
 */

export type InterrogationMetadataContext =
  (typeof InterrogationMetadataContext)[keyof typeof InterrogationMetadataContext]

export const InterrogationMetadataContext = {
  household: 'household',
  business: 'business',
} as const
