/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.4.0
 */
import type { Data } from './data'
import type { InterrogationUpdateComment } from './interrogationUpdateComment'
import type { Personalization } from './personalization'
import type { StateDataForInterrogationUpdate } from './stateDataForInterrogationUpdate'

export interface InterrogationUpdate {
  personalization?: Personalization
  data?: Data
  comment?: InterrogationUpdateComment
  stateData?: StateDataForInterrogationUpdate
}
