/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.4.0
 */
import type { Data } from './data'
import type { Personalization } from './personalization'

export interface InterrogationCreation {
  id?: string
  surveyUnitId?: string
  questionnaireId: string
  personalization?: Personalization
  data: Data
}
