/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.4.0
 */
import type { Nomenclature } from './nomenclature'

export interface NomenclatureCreation {
  id?: string
  /** @minLength 1 */
  label: string
  value: Nomenclature
}
