/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.4.0
 */

export type StateDataForInterrogationUpdateState =
  (typeof StateDataForInterrogationUpdateState)[keyof typeof StateDataForInterrogationUpdateState]

export const StateDataForInterrogationUpdateState = {
  INIT: 'INIT',
  COMPLETED: 'COMPLETED',
  VALIDATED: 'VALIDATED',
  TOEXTRACT: 'TOEXTRACT',
  EXTRACTED: 'EXTRACTED',
} as const
