/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.4.0
 */
import type { StateDataUpdateState } from './stateDataUpdateState'

export interface StateDataUpdate {
  state: StateDataUpdateState
  /** @minLength 1 */
  currentPage: string
}
