/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.4.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  Campaign,
  CampaignCreation,
  CampaignCreationV2,
  CampaignIdsDto,
  CampaignSummary,
  DeleteCampaignByIdParams,
} from '../models/api'
import { walkingPaperInstance } from './axiosInstance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Authorized roles: ADMIN / WEBCLIENT / REVIEWER / REVIEWER_ALTERNATIVE / INTERVIEWER /
 * @summary Get campaign list for the current user
 */
export const getInterviewerCampaignList = (
  options?: SecondParameter<typeof walkingPaperInstance>,
  signal?: AbortSignal,
) => {
  return walkingPaperInstance<CampaignSummary[]>(
    { url: `/api/campaigns`, method: 'GET', signal },
    options,
  )
}

export const getGetInterviewerCampaignListQueryKey = () => {
  return [`/api/campaigns`] as const
}

export const getGetInterviewerCampaignListQueryOptions = <
  TData = Awaited<ReturnType<typeof getInterviewerCampaignList>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getInterviewerCampaignList>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof walkingPaperInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetInterviewerCampaignListQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getInterviewerCampaignList>>
  > = ({ signal }) => getInterviewerCampaignList(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getInterviewerCampaignList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInterviewerCampaignListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getInterviewerCampaignList>>
>
export type GetInterviewerCampaignListQueryError = unknown

export function useGetInterviewerCampaignList<
  TData = Awaited<ReturnType<typeof getInterviewerCampaignList>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInterviewerCampaignList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterviewerCampaignList>>,
          TError,
          Awaited<ReturnType<typeof getInterviewerCampaignList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetInterviewerCampaignList<
  TData = Awaited<ReturnType<typeof getInterviewerCampaignList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInterviewerCampaignList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterviewerCampaignList>>,
          TError,
          Awaited<ReturnType<typeof getInterviewerCampaignList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetInterviewerCampaignList<
  TData = Awaited<ReturnType<typeof getInterviewerCampaignList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInterviewerCampaignList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get campaign list for the current user
 */

export function useGetInterviewerCampaignList<
  TData = Awaited<ReturnType<typeof getInterviewerCampaignList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInterviewerCampaignList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetInterviewerCampaignListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Authorized roles: ADMIN / WEBCLIENT /
 * @deprecated
 * @summary Create a campaign
 */
export const createCampaign = (
  campaignCreation: CampaignCreation,
  options?: SecondParameter<typeof walkingPaperInstance>,
  signal?: AbortSignal,
) => {
  return walkingPaperInstance<void>(
    {
      url: `/api/campaigns`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: campaignCreation,
      signal,
    },
    options,
  )
}

export const getCreateCampaignMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCampaign>>,
    TError,
    { data: CampaignCreation },
    TContext
  >
  request?: SecondParameter<typeof walkingPaperInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCampaign>>,
  TError,
  { data: CampaignCreation },
  TContext
> => {
  const mutationKey = ['createCampaign']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCampaign>>,
    { data: CampaignCreation }
  > = (props) => {
    const { data } = props ?? {}

    return createCampaign(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateCampaignMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCampaign>>
>
export type CreateCampaignMutationBody = CampaignCreation
export type CreateCampaignMutationError = unknown

/**
 * @deprecated
 * @summary Create a campaign
 */
export const useCreateCampaign = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCampaign>>,
      TError,
      { data: CampaignCreation },
      TContext
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createCampaign>>,
  TError,
  { data: CampaignCreation },
  TContext
> => {
  const mutationOptions = getCreateCampaignMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Authorized roles: ADMIN / WEBCLIENT /
 * @summary Create a campaign
 */
export const createCampaignV2 = (
  campaignCreationV2: CampaignCreationV2,
  options?: SecondParameter<typeof walkingPaperInstance>,
  signal?: AbortSignal,
) => {
  return walkingPaperInstance<void>(
    {
      url: `/api/campaign`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: campaignCreationV2,
      signal,
    },
    options,
  )
}

export const getCreateCampaignV2MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCampaignV2>>,
    TError,
    { data: CampaignCreationV2 },
    TContext
  >
  request?: SecondParameter<typeof walkingPaperInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCampaignV2>>,
  TError,
  { data: CampaignCreationV2 },
  TContext
> => {
  const mutationKey = ['createCampaignV2']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCampaignV2>>,
    { data: CampaignCreationV2 }
  > = (props) => {
    const { data } = props ?? {}

    return createCampaignV2(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateCampaignV2MutationResult = NonNullable<
  Awaited<ReturnType<typeof createCampaignV2>>
>
export type CreateCampaignV2MutationBody = CampaignCreationV2
export type CreateCampaignV2MutationError = unknown

/**
 * @summary Create a campaign
 */
export const useCreateCampaignV2 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCampaignV2>>,
      TError,
      { data: CampaignCreationV2 },
      TContext
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createCampaignV2>>,
  TError,
  { data: CampaignCreationV2 },
  TContext
> => {
  const mutationOptions = getCreateCampaignV2MutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Authorized roles: ADMIN / WEBCLIENT /
 * @summary Get list of all campaigns ids
 */
export const getListCampaignsIds = (
  options?: SecondParameter<typeof walkingPaperInstance>,
  signal?: AbortSignal,
) => {
  return walkingPaperInstance<CampaignIdsDto[]>(
    { url: `/api/campaigns/ids`, method: 'GET', signal },
    options,
  )
}

export const getGetListCampaignsIdsQueryKey = () => {
  return [`/api/campaigns/ids`] as const
}

export const getGetListCampaignsIdsQueryOptions = <
  TData = Awaited<ReturnType<typeof getListCampaignsIds>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getListCampaignsIds>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof walkingPaperInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetListCampaignsIdsQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getListCampaignsIds>>
  > = ({ signal }) => getListCampaignsIds(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getListCampaignsIds>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListCampaignsIdsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getListCampaignsIds>>
>
export type GetListCampaignsIdsQueryError = unknown

export function useGetListCampaignsIds<
  TData = Awaited<ReturnType<typeof getListCampaignsIds>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getListCampaignsIds>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListCampaignsIds>>,
          TError,
          Awaited<ReturnType<typeof getListCampaignsIds>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetListCampaignsIds<
  TData = Awaited<ReturnType<typeof getListCampaignsIds>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getListCampaignsIds>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListCampaignsIds>>,
          TError,
          Awaited<ReturnType<typeof getListCampaignsIds>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetListCampaignsIds<
  TData = Awaited<ReturnType<typeof getListCampaignsIds>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getListCampaignsIds>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get list of all campaigns ids
 */

export function useGetListCampaignsIds<
  TData = Awaited<ReturnType<typeof getListCampaignsIds>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getListCampaignsIds>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetListCampaignsIdsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Authorized roles: ADMIN / WEBCLIENT /
 * @summary Get list of all campaigns
 */
export const getListCampaign = (
  options?: SecondParameter<typeof walkingPaperInstance>,
  signal?: AbortSignal,
) => {
  return walkingPaperInstance<CampaignSummary[]>(
    { url: `/api/admin/campaigns`, method: 'GET', signal },
    options,
  )
}

export const getGetListCampaignQueryKey = () => {
  return [`/api/admin/campaigns`] as const
}

export const getGetListCampaignQueryOptions = <
  TData = Awaited<ReturnType<typeof getListCampaign>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getListCampaign>>, TError, TData>
  >
  request?: SecondParameter<typeof walkingPaperInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetListCampaignQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getListCampaign>>> = ({
    signal,
  }) => getListCampaign(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getListCampaign>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListCampaignQueryResult = NonNullable<
  Awaited<ReturnType<typeof getListCampaign>>
>
export type GetListCampaignQueryError = unknown

export function useGetListCampaign<
  TData = Awaited<ReturnType<typeof getListCampaign>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getListCampaign>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListCampaign>>,
          TError,
          Awaited<ReturnType<typeof getListCampaign>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetListCampaign<
  TData = Awaited<ReturnType<typeof getListCampaign>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getListCampaign>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListCampaign>>,
          TError,
          Awaited<ReturnType<typeof getListCampaign>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetListCampaign<
  TData = Awaited<ReturnType<typeof getListCampaign>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getListCampaign>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get list of all campaigns
 */

export function useGetListCampaign<
  TData = Awaited<ReturnType<typeof getListCampaign>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getListCampaign>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetListCampaignQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Authorized roles: ADMIN / WEBCLIENT /
 * @summary Get campaign
 */
export const getCampaign = (
  id: string,
  options?: SecondParameter<typeof walkingPaperInstance>,
  signal?: AbortSignal,
) => {
  return walkingPaperInstance<Campaign>(
    { url: `/api/admin/campaigns/${id}`, method: 'GET', signal },
    options,
  )
}

export const getGetCampaignQueryKey = (id?: string) => {
  return [`/api/admin/campaigns/${id}`] as const
}

export const getGetCampaignQueryOptions = <
  TData = Awaited<ReturnType<typeof getCampaign>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCampaign>>, TError, TData>
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetCampaignQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCampaign>>> = ({
    signal,
  }) => getCampaign(id, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCampaign>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCampaignQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCampaign>>
>
export type GetCampaignQueryError = unknown

export function useGetCampaign<
  TData = Awaited<ReturnType<typeof getCampaign>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCampaign>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCampaign>>,
          TError,
          Awaited<ReturnType<typeof getCampaign>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetCampaign<
  TData = Awaited<ReturnType<typeof getCampaign>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCampaign>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCampaign>>,
          TError,
          Awaited<ReturnType<typeof getCampaign>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetCampaign<
  TData = Awaited<ReturnType<typeof getCampaign>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCampaign>>, TError, TData>
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get campaign
 */

export function useGetCampaign<
  TData = Awaited<ReturnType<typeof getCampaign>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCampaign>>, TError, TData>
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetCampaignQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Authorized roles: ADMIN / WEBCLIENT /
 * @summary Delete a campaign
 */
export const deleteCampaignById = (
  id: string,
  params: DeleteCampaignByIdParams,
  options?: SecondParameter<typeof walkingPaperInstance>,
) => {
  return walkingPaperInstance<void>(
    { url: `/api/campaign/${id}`, method: 'DELETE', params },
    options,
  )
}

export const getDeleteCampaignByIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCampaignById>>,
    TError,
    { id: string; params: DeleteCampaignByIdParams },
    TContext
  >
  request?: SecondParameter<typeof walkingPaperInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCampaignById>>,
  TError,
  { id: string; params: DeleteCampaignByIdParams },
  TContext
> => {
  const mutationKey = ['deleteCampaignById']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCampaignById>>,
    { id: string; params: DeleteCampaignByIdParams }
  > = (props) => {
    const { id, params } = props ?? {}

    return deleteCampaignById(id, params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteCampaignByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCampaignById>>
>

export type DeleteCampaignByIdMutationError = unknown

/**
 * @summary Delete a campaign
 */
export const useDeleteCampaignById = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCampaignById>>,
      TError,
      { id: string; params: DeleteCampaignByIdParams },
      TContext
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteCampaignById>>,
  TError,
  { id: string; params: DeleteCampaignByIdParams },
  TContext
> => {
  const mutationOptions = getDeleteCampaignByIdMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
