/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.4.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  GetQuestionnaireData200,
  InterrogationsOkNok,
  QuestionnaireModelCreation,
  QuestionnaireModelId,
  QuestionnaireModelValue,
} from '../models/api'
import { walkingPaperInstance } from './axiosInstance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Authorized roles: ADMIN / WEBCLIENT /
 * @summary Create a Questionnaire Model
 */
export const createQuestionnaire = (
  questionnaireModelCreation: QuestionnaireModelCreation,
  options?: SecondParameter<typeof walkingPaperInstance>,
  signal?: AbortSignal,
) => {
  return walkingPaperInstance<void>(
    {
      url: `/api/questionnaire-models`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: questionnaireModelCreation,
      signal,
    },
    options,
  )
}

export const getCreateQuestionnaireMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createQuestionnaire>>,
    TError,
    { data: QuestionnaireModelCreation },
    TContext
  >
  request?: SecondParameter<typeof walkingPaperInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createQuestionnaire>>,
  TError,
  { data: QuestionnaireModelCreation },
  TContext
> => {
  const mutationKey = ['createQuestionnaire']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createQuestionnaire>>,
    { data: QuestionnaireModelCreation }
  > = (props) => {
    const { data } = props ?? {}

    return createQuestionnaire(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateQuestionnaireMutationResult = NonNullable<
  Awaited<ReturnType<typeof createQuestionnaire>>
>
export type CreateQuestionnaireMutationBody = QuestionnaireModelCreation
export type CreateQuestionnaireMutationError = unknown

/**
 * @summary Create a Questionnaire Model
 */
export const useCreateQuestionnaire = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createQuestionnaire>>,
      TError,
      { data: QuestionnaireModelCreation },
      TContext
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createQuestionnaire>>,
  TError,
  { data: QuestionnaireModelCreation },
  TContext
> => {
  const mutationOptions = getCreateQuestionnaireMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Authorized roles: ADMIN / WEBCLIENT / REVIEWER / REVIEWER_ALTERNATIVE / INTERVIEWER /
 * @summary Search questionnaire ids linked to interrogations
 */
export const getQuestionnaireModelIdByInterrogations = (
  getQuestionnaireModelIdByInterrogationsBody: string[],
  options?: SecondParameter<typeof walkingPaperInstance>,
  signal?: AbortSignal,
) => {
  return walkingPaperInstance<InterrogationsOkNok>(
    {
      url: `/api/interrogations/questionnaire-model-id`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: getQuestionnaireModelIdByInterrogationsBody,
      signal,
    },
    options,
  )
}

export const getGetQuestionnaireModelIdByInterrogationsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getQuestionnaireModelIdByInterrogations>>,
    TError,
    { data: string[] },
    TContext
  >
  request?: SecondParameter<typeof walkingPaperInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof getQuestionnaireModelIdByInterrogations>>,
  TError,
  { data: string[] },
  TContext
> => {
  const mutationKey = ['getQuestionnaireModelIdByInterrogations']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getQuestionnaireModelIdByInterrogations>>,
    { data: string[] }
  > = (props) => {
    const { data } = props ?? {}

    return getQuestionnaireModelIdByInterrogations(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type GetQuestionnaireModelIdByInterrogationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof getQuestionnaireModelIdByInterrogations>>
>
export type GetQuestionnaireModelIdByInterrogationsMutationBody = string[]
export type GetQuestionnaireModelIdByInterrogationsMutationError = unknown

/**
 * @summary Search questionnaire ids linked to interrogations
 */
export const useGetQuestionnaireModelIdByInterrogations = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof getQuestionnaireModelIdByInterrogations>>,
      TError,
      { data: string[] },
      TContext
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof getQuestionnaireModelIdByInterrogations>>,
  TError,
  { data: string[] },
  TContext
> => {
  const mutationOptions =
    getGetQuestionnaireModelIdByInterrogationsMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Authorized roles: ADMIN / WEBCLIENT / REVIEWER / REVIEWER_ALTERNATIVE / INTERVIEWER / SURVEY_UNIT /
 * @deprecated
 * @summary Get questionnnaire
 */
export const getQuestionnaireValue = (
  id: string,
  options?: SecondParameter<typeof walkingPaperInstance>,
  signal?: AbortSignal,
) => {
  return walkingPaperInstance<QuestionnaireModelValue>(
    { url: `/api/questionnaire/${id}`, method: 'GET', signal },
    options,
  )
}

export const getGetQuestionnaireValueQueryKey = (id?: string) => {
  return [`/api/questionnaire/${id}`] as const
}

export const getGetQuestionnaireValueQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuestionnaireValue>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireValue>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetQuestionnaireValueQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getQuestionnaireValue>>
  > = ({ signal }) => getQuestionnaireValue(id, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getQuestionnaireValue>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestionnaireValueQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestionnaireValue>>
>
export type GetQuestionnaireValueQueryError = unknown

export function useGetQuestionnaireValue<
  TData = Awaited<ReturnType<typeof getQuestionnaireValue>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireValue>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionnaireValue>>,
          TError,
          Awaited<ReturnType<typeof getQuestionnaireValue>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetQuestionnaireValue<
  TData = Awaited<ReturnType<typeof getQuestionnaireValue>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireValue>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionnaireValue>>,
          TError,
          Awaited<ReturnType<typeof getQuestionnaireValue>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetQuestionnaireValue<
  TData = Awaited<ReturnType<typeof getQuestionnaireValue>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireValue>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @deprecated
 * @summary Get questionnnaire
 */

export function useGetQuestionnaireValue<
  TData = Awaited<ReturnType<typeof getQuestionnaireValue>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireValue>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetQuestionnaireValueQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Authorized roles: ADMIN / WEBCLIENT / REVIEWER / REVIEWER_ALTERNATIVE / INTERVIEWER / SURVEY_UNIT /
 * @summary Get questionnnaire data
 */
export const getQuestionnaireData = (
  id: string,
  options?: SecondParameter<typeof walkingPaperInstance>,
  signal?: AbortSignal,
) => {
  return walkingPaperInstance<GetQuestionnaireData200>(
    { url: `/api/questionnaire/${id}/data`, method: 'GET', signal },
    options,
  )
}

export const getGetQuestionnaireDataQueryKey = (id?: string) => {
  return [`/api/questionnaire/${id}/data`] as const
}

export const getGetQuestionnaireDataQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuestionnaireData>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireData>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetQuestionnaireDataQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getQuestionnaireData>>
  > = ({ signal }) => getQuestionnaireData(id, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getQuestionnaireData>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestionnaireDataQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestionnaireData>>
>
export type GetQuestionnaireDataQueryError = unknown

export function useGetQuestionnaireData<
  TData = Awaited<ReturnType<typeof getQuestionnaireData>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireData>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionnaireData>>,
          TError,
          Awaited<ReturnType<typeof getQuestionnaireData>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetQuestionnaireData<
  TData = Awaited<ReturnType<typeof getQuestionnaireData>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireData>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionnaireData>>,
          TError,
          Awaited<ReturnType<typeof getQuestionnaireData>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetQuestionnaireData<
  TData = Awaited<ReturnType<typeof getQuestionnaireData>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireData>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get questionnnaire data
 */

export function useGetQuestionnaireData<
  TData = Awaited<ReturnType<typeof getQuestionnaireData>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireData>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetQuestionnaireDataQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Authorized roles: ADMIN / WEBCLIENT / REVIEWER / REVIEWER_ALTERNATIVE / INTERVIEWER /
 * @summary Get questionnaire list for a campaign
 */
export const getQuestionnaireDatasByCampaignId = (
  id: string,
  options?: SecondParameter<typeof walkingPaperInstance>,
  signal?: AbortSignal,
) => {
  return walkingPaperInstance<QuestionnaireModelValue[]>(
    { url: `/api/campaign/${id}/questionnaires`, method: 'GET', signal },
    options,
  )
}

export const getGetQuestionnaireDatasByCampaignIdQueryKey = (id?: string) => {
  return [`/api/campaign/${id}/questionnaires`] as const
}

export const getGetQuestionnaireDatasByCampaignIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetQuestionnaireDatasByCampaignIdQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>
  > = ({ signal }) =>
    getQuestionnaireDatasByCampaignId(id, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestionnaireDatasByCampaignIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>
>
export type GetQuestionnaireDatasByCampaignIdQueryError = unknown

export function useGetQuestionnaireDatasByCampaignId<
  TData = Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
          TError,
          Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetQuestionnaireDatasByCampaignId<
  TData = Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
          TError,
          Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetQuestionnaireDatasByCampaignId<
  TData = Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get questionnaire list for a campaign
 */

export function useGetQuestionnaireDatasByCampaignId<
  TData = Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireDatasByCampaignId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetQuestionnaireDatasByCampaignIdQueryOptions(
    id,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Authorized roles: ADMIN / WEBCLIENT / REVIEWER / REVIEWER_ALTERNATIVE / INTERVIEWER /
 * @summary Get list of questionnaire ids for a campaign
 */
export const getQuestionnaireIdsByCampaignId = (
  id: string,
  options?: SecondParameter<typeof walkingPaperInstance>,
  signal?: AbortSignal,
) => {
  return walkingPaperInstance<QuestionnaireModelId[]>(
    { url: `/api/campaign/${id}/questionnaire-id`, method: 'GET', signal },
    options,
  )
}

export const getGetQuestionnaireIdsByCampaignIdQueryKey = (id?: string) => {
  return [`/api/campaign/${id}/questionnaire-id`] as const
}

export const getGetQuestionnaireIdsByCampaignIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetQuestionnaireIdsByCampaignIdQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>
  > = ({ signal }) =>
    getQuestionnaireIdsByCampaignId(id, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestionnaireIdsByCampaignIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>
>
export type GetQuestionnaireIdsByCampaignIdQueryError = unknown

export function useGetQuestionnaireIdsByCampaignId<
  TData = Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
          TError,
          Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetQuestionnaireIdsByCampaignId<
  TData = Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
          TError,
          Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetQuestionnaireIdsByCampaignId<
  TData = Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get list of questionnaire ids for a campaign
 */

export function useGetQuestionnaireIdsByCampaignId<
  TData = Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestionnaireIdsByCampaignId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetQuestionnaireIdsByCampaignIdQueryOptions(
    id,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}
