/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.4.0
 */
import { useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type { Metadata } from '../models/api'
import { walkingPaperInstance } from './axiosInstance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Authorized roles: ADMIN / WEBCLIENT / REVIEWER / REVIEWER_ALTERNATIVE / INTERVIEWER / SURVEY_UNIT /
 * @summary Get metadata for a questionnaire
 */
export const getMetadataByQuestionnaireId = (
  id: string,
  options?: SecondParameter<typeof walkingPaperInstance>,
  signal?: AbortSignal,
) => {
  return walkingPaperInstance<Metadata>(
    { url: `/api/questionnaire/${id}/metadata`, method: 'GET', signal },
    options,
  )
}

export const getGetMetadataByQuestionnaireIdQueryKey = (id?: string) => {
  return [`/api/questionnaire/${id}/metadata`] as const
}

export const getGetMetadataByQuestionnaireIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getMetadataByQuestionnaireId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMetadataByQuestionnaireId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetMetadataByQuestionnaireIdQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMetadataByQuestionnaireId>>
  > = ({ signal }) => getMetadataByQuestionnaireId(id, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMetadataByQuestionnaireId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMetadataByQuestionnaireIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMetadataByQuestionnaireId>>
>
export type GetMetadataByQuestionnaireIdQueryError = unknown

export function useGetMetadataByQuestionnaireId<
  TData = Awaited<ReturnType<typeof getMetadataByQuestionnaireId>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMetadataByQuestionnaireId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMetadataByQuestionnaireId>>,
          TError,
          Awaited<ReturnType<typeof getMetadataByQuestionnaireId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetMetadataByQuestionnaireId<
  TData = Awaited<ReturnType<typeof getMetadataByQuestionnaireId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMetadataByQuestionnaireId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMetadataByQuestionnaireId>>,
          TError,
          Awaited<ReturnType<typeof getMetadataByQuestionnaireId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetMetadataByQuestionnaireId<
  TData = Awaited<ReturnType<typeof getMetadataByQuestionnaireId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMetadataByQuestionnaireId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get metadata for a questionnaire
 */

export function useGetMetadataByQuestionnaireId<
  TData = Awaited<ReturnType<typeof getMetadataByQuestionnaireId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMetadataByQuestionnaireId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetMetadataByQuestionnaireIdQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Authorized roles: ADMIN / WEBCLIENT / REVIEWER / REVIEWER_ALTERNATIVE / INTERVIEWER / SURVEY_UNIT /
 * @summary Get metadata for a campaign
 */
export const getMetadataByCampaignId = (
  id: string,
  options?: SecondParameter<typeof walkingPaperInstance>,
  signal?: AbortSignal,
) => {
  return walkingPaperInstance<Metadata>(
    { url: `/api/campaign/${id}/metadata`, method: 'GET', signal },
    options,
  )
}

export const getGetMetadataByCampaignIdQueryKey = (id?: string) => {
  return [`/api/campaign/${id}/metadata`] as const
}

export const getGetMetadataByCampaignIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getMetadataByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMetadataByCampaignId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetMetadataByCampaignIdQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMetadataByCampaignId>>
  > = ({ signal }) => getMetadataByCampaignId(id, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMetadataByCampaignId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMetadataByCampaignIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMetadataByCampaignId>>
>
export type GetMetadataByCampaignIdQueryError = unknown

export function useGetMetadataByCampaignId<
  TData = Awaited<ReturnType<typeof getMetadataByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMetadataByCampaignId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMetadataByCampaignId>>,
          TError,
          Awaited<ReturnType<typeof getMetadataByCampaignId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetMetadataByCampaignId<
  TData = Awaited<ReturnType<typeof getMetadataByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMetadataByCampaignId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMetadataByCampaignId>>,
          TError,
          Awaited<ReturnType<typeof getMetadataByCampaignId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetMetadataByCampaignId<
  TData = Awaited<ReturnType<typeof getMetadataByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMetadataByCampaignId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get metadata for a campaign
 */

export function useGetMetadataByCampaignId<
  TData = Awaited<ReturnType<typeof getMetadataByCampaignId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMetadataByCampaignId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetMetadataByCampaignIdQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}
