/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.4.0
 */
import { useMutation } from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query'

import type { AddParadataBody } from '../models/api'
import { walkingPaperInstance } from './axiosInstance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Authorized roles: ADMIN / WEBCLIENT / REVIEWER / REVIEWER_ALTERNATIVE / INTERVIEWER / SURVEY_UNIT /
 * @summary Create paradata event for an interrogation
 */
export const addParadata = (
  addParadataBody: AddParadataBody,
  options?: SecondParameter<typeof walkingPaperInstance>,
  signal?: AbortSignal,
) => {
  return walkingPaperInstance<void>(
    {
      url: `/api/paradata`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: addParadataBody,
      signal,
    },
    options,
  )
}

export const getAddParadataMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addParadata>>,
    TError,
    { data: AddParadataBody },
    TContext
  >
  request?: SecondParameter<typeof walkingPaperInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof addParadata>>,
  TError,
  { data: AddParadataBody },
  TContext
> => {
  const mutationKey = ['addParadata']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addParadata>>,
    { data: AddParadataBody }
  > = (props) => {
    const { data } = props ?? {}

    return addParadata(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AddParadataMutationResult = NonNullable<
  Awaited<ReturnType<typeof addParadata>>
>
export type AddParadataMutationBody = AddParadataBody
export type AddParadataMutationError = unknown

/**
 * @summary Create paradata event for an interrogation
 */
export const useAddParadata = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addParadata>>,
      TError,
      { data: AddParadataBody },
      TContext
    >
    request?: SecondParameter<typeof walkingPaperInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addParadata>>,
  TError,
  { data: AddParadataBody },
  TContext
> => {
  const mutationOptions = getAddParadataMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
