/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualizeIndexRouteImport } from './routes/visualize/index'

const VisualizeIndexRoute = VisualizeIndexRouteImport.update({
  id: '/visualize/',
  path: '/visualize/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/visualize': typeof VisualizeIndexRoute
}
export interface FileRoutesByTo {
  '/visualize': typeof VisualizeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/visualize/': typeof VisualizeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/visualize'
  fileRoutesByTo: FileRoutesByTo
  to: '/visualize'
  id: '__root__' | '/visualize/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  VisualizeIndexRoute: typeof VisualizeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visualize/': {
      id: '/visualize/'
      path: '/visualize'
      fullPath: '/visualize'
      preLoaderRoute: typeof VisualizeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  VisualizeIndexRoute: VisualizeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
