/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualizeIndexRouteImport } from './routes/visualize/index'
import { Route as InterrogationsInterrogationIdRouteImport } from './routes/interrogations/$interrogationId'

const VisualizeIndexRoute = VisualizeIndexRouteImport.update({
  id: '/visualize/',
  path: '/visualize/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterrogationsInterrogationIdRoute =
  InterrogationsInterrogationIdRouteImport.update({
    id: '/interrogations/$interrogationId',
    path: '/interrogations/$interrogationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/interrogations/$interrogationId': typeof InterrogationsInterrogationIdRoute
  '/visualize': typeof VisualizeIndexRoute
}
export interface FileRoutesByTo {
  '/interrogations/$interrogationId': typeof InterrogationsInterrogationIdRoute
  '/visualize': typeof VisualizeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/interrogations/$interrogationId': typeof InterrogationsInterrogationIdRoute
  '/visualize/': typeof VisualizeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/interrogations/$interrogationId' | '/visualize'
  fileRoutesByTo: FileRoutesByTo
  to: '/interrogations/$interrogationId' | '/visualize'
  id: '__root__' | '/interrogations/$interrogationId' | '/visualize/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  InterrogationsInterrogationIdRoute: typeof InterrogationsInterrogationIdRoute
  VisualizeIndexRoute: typeof VisualizeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visualize/': {
      id: '/visualize/'
      path: '/visualize'
      fullPath: '/visualize'
      preLoaderRoute: typeof VisualizeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interrogations/$interrogationId': {
      id: '/interrogations/$interrogationId'
      path: '/interrogations/$interrogationId'
      fullPath: '/interrogations/$interrogationId'
      preLoaderRoute: typeof InterrogationsInterrogationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  InterrogationsInterrogationIdRoute: InterrogationsInterrogationIdRoute,
  VisualizeIndexRoute: VisualizeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
